# For a quick start check out our HTTP Requests collection (Tools|HTTP Client|Open HTTP Requests Collection).
#
# Following HTTP Request Live Templates are available:
# * 'gtrp' and 'gtr' create a GET request with or without query parameters;
# * 'ptr' and 'ptrp' create a POST request with a simple or parameter-like body;
# * 'mptr' and 'fptr' create a POST request to submit a form with a text or file field (multipart/form-data);

GET http://localhost:8080/comment/list
Accept: application/json

###
POST http://localhost:8080/user/add
Content-Type: application/json

{
  "username": "b",
  "email": "b@dgsw",
  "password" : "1234"
}

###
GET http://localhost:8080/user/list
Accept: application/json

###
GET http://localhost:8080/user/view/1
Accept: application/json

###
PUT http://localhost:8080/user/update/1
Content-Type: application/json

{
  "email": "ccc@dgswww"
}

###
DELETE http://localhost:8080/user/delete/1
Accept: application/json

###
GET http://localhost:8080/comment/view/1
Accept: application/json

###
PUT http://localhost:8080/comment/update/3
Content-Type: application/json

{
  "user_id": 1,
  "comment": "hi"
}

###
DELETE http://localhost:8080/comment/delete/1
Accept: application/json

###
POST http://localhost:8080/comment/add
Content-Type: application/json

{
  "user_id": 1,
  "comment": "hello~"
}

###
POST http://localhost:8080/user/login
Content-Type: application/json

{
  "email": "ccc@dgswww",
  "password": "1234"
}

###
GET http://localhost:8080/api/v1/movies/기생충
Content-Type: application/json